
spring:
  datasource:
    url: jdbc:h2:~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

